# Generated by Django 4.2.5 on 2023-10-23 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_announcements_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcements',
            name='file',
        ),
        migrations.CreateModel(
            name='AnnouncementFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='announce/')),
                ('announce', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='main.announcements')),
            ],
        ),
    ]
