# Generated by Django 4.2.5 on 2023-10-31 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('main', '0015_course_grades'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Userm',
        ),
    ]
