# Generated by Django 4.2.5 on 2023-11-01 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_user_branch_announcementscourse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcementscourse',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='main.course'),
        ),
    ]
