# Generated by Django 4.2.5 on 2023-11-01 18:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_alter_announcementfilescourse_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('total_marks', models.IntegerField()),
                ('closing_date', models.DateField()),
                ('closing_time', models.TimeField()),
                ('source_file', models.FileField(blank=True, null=True, upload_to='assignments/')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='main.course')),
            ],
        ),
        migrations.CreateModel(
            name='AssignmentSub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks_given', models.IntegerField(default=0)),
                ('fileUpload', models.FileField(upload_to='assignments/')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.assignment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignmentsSub', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
