# Generated by Django 4.2.5 on 2023-11-01 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_assignment_is_submitted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentsub',
            name='fileUpload',
            field=models.FileField(blank=True, null=True, upload_to='assignments/'),
        ),
        migrations.CreateModel(
            name='Resources',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='main.course')),
            ],
        ),
    ]
