# Generated by Django 4.2.5 on 2023-11-01 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_alter_assignmentsub_fileupload_resources'),
    ]

    operations = [
        migrations.AddField(
            model_name='resources',
            name='file_res',
            field=models.FileField(blank=True, null=True, upload_to='announce/'),
        ),
    ]
