# Generated by Django 4.2.5 on 2023-11-01 20:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_alter_resources_file_res'),
    ]

    operations = [
        migrations.AddField(
            model_name='resources',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
