# Generated by Django 4.2.5 on 2023-11-02 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='main.course'),
        ),
    ]
