# Generated by Django 4.2.5 on 2023-11-03 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_alter_room_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='grades',
            name='is_graded',
            field=models.BooleanField(default=False),
        ),
    ]
