# Generated by Django 4.2.5 on 2023-11-04 07:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_remove_attendence_back_listed_room_back_listed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendence',
            name='course',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendCards', to='main.course'),
        ),
        migrations.AlterField(
            model_name='attendence',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendCards', to=settings.AUTH_USER_MODEL),
        ),
    ]
