# Generated by Django 4.2.5 on 2023-11-04 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_alter_attendence_course_alter_attendence_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendence',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendCards', to='main.course'),
        ),
    ]
