# Generated by Django 4.2.5 on 2023-11-04 08:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_alter_attendence_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendence',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendCards', to='main.course'),
        ),
        migrations.AlterField(
            model_name='attendence',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendCards', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='room',
            name='back_listed',
            field=models.ManyToManyField(blank=True, null=True, related_name='roomsStuBack', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='room',
            name='students',
            field=models.ManyToManyField(blank=True, null=True, related_name='roomsStu', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='room',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roomsTea', to=settings.AUTH_USER_MODEL),
        ),
    ]
