# Generated by Django 4.2.5 on 2023-11-04 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_alter_attendence_course_alter_attendence_student_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='is_finished',
            field=models.BooleanField(default=False),
        ),
    ]
